application: holstedgrandprix
version: v2
runtime: go
api_version: go1

handlers:
- url: /
  static_files: client/html/index.html
  upload: client/html/index.html
  secure: always

- url: /admin.html
  static_files: client/html/admin.html
  upload: client/html/admin.html
  secure: always
  login: admin

- url: /js
  static_dir: client/html/js

- url: /css
  static_dir: client/html/css

- url: /partials
  static_dir: client/html/partials

- url: /images
  static_dir: client/html/images

- url: /2016
  static_dir: client/html/2016

- url: /.*
  script: _go_app

# - url: /resources/.*
#   script: _go_app

# Important! Even though there's a catch all routing above,
# without these two lines it's not going to work.
# Make sure you have this:
- url: /_ah/spi/.*
  script: _go_app
